### ISSUE TITLE
Update links in DOCUMENTATION.md

### ISSUE THREAD

**Issue by nadchif** [nadchif/phone-resolution-tool#2]
Great for first timers.

Change 
`https://drive.google.com/file/d/1Z9Hed4TrsdPZctBhqjzYwgKLKTAFvwpK/view?usp=drivesdk`
 to 
`https://forum.xda-developers.com/attachment.php?attachmentid=4995301&d=1586976826`
 on line 17 of [DOCUMENTATION.md](https://github.com/nadchif/phone-resolution-tool/blob/master/DOCUMENTATION.md)

For a step by step guide on how to do this. See [CONTRIBUTING.md](https://github.com/nadchif/phone-resolution-tool/blob/master/CONTRIBUTING.md)

NOTE TO EXPERIENCED USERS: Please leave this issue for users who are new or first timers to OSS. This provides them an opportunity to learn Open Source Contribution workflow.

**Comment by nadchif** [comment]
@all-contributors please add @nadchif for code, tests and maintenance

**Comment by aldrinjenson** [comment]
Hi, can i work on this?

**Comment by nadchif** [comment]
@aldrinjenson yes, sure 😄

**Comment by aldrinjenson** [comment]
@nadchif Thank you! I have created a pull request. Hope its alright!

**Comment by nadchif** [comment]
Thank you @aldrinjenson . Good job!
